<Workspace Version="1.1.1.1841" X="-70.851349616716" Y="155.821163687476" zoom="1.24844365397223" Name="Springs.Element.Copy" Description="WARNING: Do not use this node in Automatic mode! Copy (planar array) the input Revit elements with the help of a translation vector, similarly to the Geometry.Translate node." ID="cba6fef1-c536-4337-ba89-2a1aedbbbef2" Category="Springs.Revit.Element">
  <NamespaceResolutionMap>
    <ClassMap partialName="Rectangle" resolvedName="Autodesk.DesignScript.Geometry.Rectangle" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Sphere" resolvedName="Autodesk.DesignScript.Geometry.Sphere" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Cuboid" resolvedName="Autodesk.DesignScript.Geometry.Cuboid" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Plane.XY" resolvedName="Autodesk.DesignScript.Geometry.Plane" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Plane" resolvedName="Autodesk.DesignScript.Geometry.Plane" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="07c44ee4-0bfc-458b-98f6-efbc66bd25a6" type="PythonNodeModels.PythonNode" nickname="Python Script" x="249.199002696823" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <Script>#Copyright(c) 2016, Dimitar Venkov
# @5devene, dimitar.ven@gmail.com

import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *

ele = UnwrapElement(IN[0])
vec = tolist(IN[1])

try:
	TransactionManager.Instance.EnsureInTransaction(doc)
	newId = ElementTransformUtils.CopyElement(doc, ele.Id, vec.ToXyz(True) )
	TransactionManager.Instance.TransactionTaskDone()
	res1 = [doc.GetElement(newId[i]).ToDSType(False) for i in xrange(len(newId) )]
except: res1 = []

OUT = res1</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="aca08315-87ef-44c6-9803-4da4b8812901" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="398.218909571098" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="element(s)" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="ff0ecd91-e81d-4c57-b042-6b3a6d69447e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="89.5999999999999" y="-4.40000000000003" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="element:var" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="813d0625-79a5-4345-b8cd-7bb2e8a0dcb9" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="92.7240489683078" y="58.9725683837867" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="vector:var" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="07c44ee4-0bfc-458b-98f6-efbc66bd25a6" start_index="0" end="aca08315-87ef-44c6-9803-4da4b8812901" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ff0ecd91-e81d-4c57-b042-6b3a6d69447e" start_index="0" end="07c44ee4-0bfc-458b-98f6-efbc66bd25a6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="813d0625-79a5-4345-b8cd-7bb2e8a0dcb9" start_index="0" end="07c44ee4-0bfc-458b-98f6-efbc66bd25a6" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>