<Workspace Version="0.8.2.2392" X="105.6" Y="210.4" zoom="1" Name="Select Edges" Description="Select multiple edges from inside the Revit UI. Be sure to press &quot;Finish&quot; once done. You can use a Boolean toggle to refresh your selection." ID="900c22e1-0838-4722-b3a6-b2642d93d03b" Category="SpringNodes.Revit.Selection">
  <NamespaceResolutionMap />
  <Elements>
    <DSIronPythonNode.PythonNode guid="02ea08f7-6e03-4cec-a0ed-f91926739fd3" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>#select multiple edges in Revit and convert to Dynamo geometry

import clr

clr.AddReference("RevitAPIUI")
from  Autodesk.Revit.UI import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

sel1 = uidoc.Selection
ot1 = Selection.ObjectType.Edge
refs = sel1.PickObjects(ot1, "Select the desired edges and press Finish")
edges = []
for r in refs:
	el1 = doc.GetElement(r.ElementId)
	edge = el1.GetGeometryObjectFromReference(r)
	edges.append(edge.AsCurve().ToProtoType())
OUT = edges</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.Output guid="1c9385b4-6fe9-47c9-b5fc-d7f80b271887" type="Dynamo.Nodes.Output" nickname="Output" x="391.4" y="0.350718471506397" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="edges" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Symbol guid="964c67f3-44cf-4ff3-a86f-b2484ee2fac7" type="Dynamo.Nodes.Symbol" nickname="Input" x="42.8" y="0.399999999999977" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="refresh:bool = true" />
    </Dynamo.Nodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="02ea08f7-6e03-4cec-a0ed-f91926739fd3" start_index="0" end="1c9385b4-6fe9-47c9-b5fc-d7f80b271887" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="964c67f3-44cf-4ff3-a86f-b2484ee2fac7" start_index="0" end="02ea08f7-6e03-4cec-a0ed-f91926739fd3" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="-1001.42901611328" eyeY="5003.68359375" eyeZ="22225.8515625" lookX="-1820.99243164063" lookY="-1032.23449707031" lookZ="-26041.404296875" />
  </Cameras>
</Workspace>