<Workspace Version="0.8.2.2392" X="59.4277092447811" Y="160.425718796257" zoom="1.78359936238281" Name="Topography.ToPolySurface(py)" Description="Python implementation that should boost performance by 5-10%. Optimized algorithm for converting topographies into polysurfaces. Tested with topographies containing up to 40 000 points. &#xD;&#xA;Warning conversions of such mangitudes consume a lot of resources and are sub-optimal. Ensure that you have at least 8GB of ram and plenty of patience before attempting such a conversion, otherwise your Dynamo and Revit instances may crash." ID="350eeaeb-d67b-4e9c-9cd9-bc5936f9905d" Category="SpringNodes.Revit.Topography">
  <NamespaceResolutionMap>
    <ClassMap partialName="Surface" resolvedName="Autodesk.DesignScript.Geometry.Surface" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Topography" resolvedName="Revit.Elements.Topography" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <DSIronPythonNode.PythonNode guid="61dd9d6c-cbd0-49e8-a1d0-b7bc45e03430" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

topo = IN[0].Mesh

def chop1(l1, n):
	return [l1[x:x+n] for x in xrange(0, len(l1), n)]

def mesh2ps(topo, f_ps1 = PolySurface.ByJoinedSurfaces,
f_sf1 = Surface.ByPerimeterPoints, f_chop = chop1):
	vp = topo.VertexPositions
	fi = topo.FaceIndices
	ind = [[fi[j].A, fi[j].B, fi[j].C] for j in xrange(len(fi))]
	ptslist = [[vp[ind[i][j]] for j in xrange(len(ind[i]))] for i in xrange(len(ind))]
	sflist = [f_sf1(pts) for pts in ptslist]
	while len(sflist) &gt; 10 :
		sflist = f_chop(sflist,10)
		sflist = [f_ps1(sf1) for sf1 in sflist]
	return f_ps1(sflist)
OUT = mesh2ps(topo)</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.Output guid="608b56c8-8f5a-4672-a122-a9432d2b9da1" type="Dynamo.Nodes.Output" nickname="Output" x="429.61609504956" y="2.24265610560445" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="polysurface" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Symbol guid="5c7aaf41-10ae-425b-94e3-e4fb3d5259f5" type="Dynamo.Nodes.Symbol" nickname="Input" x="9.76248079258971" y="-1.11328534670787" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="topography:Topography" />
    </Dynamo.Nodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="61dd9d6c-cbd0-49e8-a1d0-b7bc45e03430" start_index="0" end="608b56c8-8f5a-4672-a122-a9432d2b9da1" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="5c7aaf41-10ae-425b-94e3-e4fb3d5259f5" start_index="0" end="61dd9d6c-cbd0-49e8-a1d0-b7bc45e03430" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="3.56142687797546" eyeY="31.2306957244873" eyeZ="0.207877442240715" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
</Workspace>