<Workspace Version="0.8.2.2392" X="432.024365789832" Y="109.971029577209" zoom="0.683206694052568" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Rectangle" resolvedName="Autodesk.DesignScript.Geometry.Rectangle" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Sphere" resolvedName="Autodesk.DesignScript.Geometry.Sphere" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Cuboid" resolvedName="Autodesk.DesignScript.Geometry.Cuboid" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Plane.XY" resolvedName="Autodesk.DesignScript.Geometry.Plane" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Plane" resolvedName="Autodesk.DesignScript.Geometry.Plane" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Material" resolvedName="Revit.Elements.Material" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.CodeBlockNodeModel guid="372635db-d34e-42a7-9932-c8b426f0833d" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-584.189640692951" y="-69.3254497454216" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="r1 = Rectangle.ByWidthLength(3000,4000);&#xA;pts1 = r1.Points;&#xA;cpt = r1.Center();&#xA;s1 = Sphere.ByCenterPointRadius(pts1,800);&#xA;s2 = Sphere.ByCenterPointRadius(cpt,1700).&#xA;Translate(Vector.ByCoordinates(0,0,500));&#xA;s3 = s2.Scale(Plane.XY(),1,2,0.8);&#xA;c1 = Cuboid.ByLengths(2500,2000,1500).&#xA;Translate(Vector.ByCoordinates(0,1000,1500));&#xA;solid = s3.UnionAll(Flatten({s1,c1}));" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction guid="1e932680-c19b-445b-a6c7-6dcda1ca32bc" type="Dynamo.Nodes.DSFunction" nickname="Object.Identity" x="-154.879856613629" y="84.2315014638224" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="DSCoreNodes.dll" function="DSCore.Object.Identity@var" />
    <Dynamo.Nodes.DSFunction guid="c86c7a9a-c89d-47e6-b8e5-41b958121dd1" type="Dynamo.Nodes.DSFunction" nickname="Element.SetParameterByName" x="281.498222144645" y="85.2453269874684" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.Element.SetParameterByName@string,var" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="805a1a18-4c65-4052-bad7-628da9d888ef" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2.08463871806424" y="166.513766537246" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="&quot;Material&quot;;&#xA;Material.ByName(&quot;Glass&quot;);" ShouldFocus="false" />
    <Dynamo.Nodes.Function guid="d5ab2529-0641-4a8a-8479-e5c2d421102a" type="Dynamo.Nodes.Function" nickname="Form.ByGeometry" x="23.4491424482026" y="78.7686869503003" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False">
      <ID value="268c3e45-41fa-4d94-a91c-1a45a41b45aa" />
      <Name value="Form.ByGeometry" />
      <Description value="Attempts to convert the input geometry to a Revit Form object. Warning - use method this only in the family environment. Can convert complicated solids or surfaces directly into forms." />
      <Inputs>
        <Input value="geometry" />
      </Inputs>
      <Outputs>
        <Output value="Form" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.CodeBlockNodeModel guid="7ef11667-481e-40b4-bc5c-bddc7d3f8564" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-118.90612814305" y="-54.5385384286735" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="//make sure you're inside a family document&#xA;//foe example, try the Conceptual Mass environment&#xA;//unlike a DirectShape, it's easy to change a form's material" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="372635db-d34e-42a7-9932-c8b426f0833d" start_index="7" end="1e932680-c19b-445b-a6c7-6dcda1ca32bc" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="1e932680-c19b-445b-a6c7-6dcda1ca32bc" start_index="0" end="d5ab2529-0641-4a8a-8479-e5c2d421102a" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="805a1a18-4c65-4052-bad7-628da9d888ef" start_index="0" end="c86c7a9a-c89d-47e6-b8e5-41b958121dd1" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="805a1a18-4c65-4052-bad7-628da9d888ef" start_index="1" end="c86c7a9a-c89d-47e6-b8e5-41b958121dd1" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="d5ab2529-0641-4a8a-8479-e5c2d421102a" start_index="0" end="c86c7a9a-c89d-47e6-b8e5-41b958121dd1" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="-12642.265625" eyeY="6014.31982421875" eyeZ="7649.9677734375" lookX="12656.1630859375" lookY="-3189.5947265625" lookZ="-8861.94140625" />
  </Cameras>
</Workspace>